# Generated by Django 5.2.3 on 2025-07-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netease_id", models.IntegerField(unique=True, verbose_name="歌手ID")),
                ("name", models.CharField(max_length=100, verbose_name="歌手名")),
                (
                    "avatar_url",
                    models.URLField(max_length=500, verbose_name="歌手图片url"),
                ),
                (
                    "origin_url",
                    models.URLField(
                        default="https://music.163.com/#/artist?id=",
                        help_text="网易云音乐歌手主页URL",
                        max_length=500,
                        verbose_name="原始链接",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="歌手简介")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "歌手",
                "verbose_name_plural": "歌手列表",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.IntegerField(unique=True, verbose_name="歌曲ID")),
                ("title", models.CharField(max_length=200, verbose_name="歌曲名")),
                ("album", models.CharField(max_length=200, verbose_name="专辑名称")),
                (
                    "origin_url",
                    models.URLField(
                        blank=True,
                        help_text="网易云音乐歌曲页面URL",
                        max_length=500,
                        verbose_name="原始链接",
                    ),
                ),
                (
                    "lyrics",
                    models.TextField(
                        blank=True, help_text="歌曲完整歌词", verbose_name="歌词"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="artists.artist",
                        verbose_name="歌手名",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌曲",
                "verbose_name_plural": "歌曲列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
