# Generated by Django 5.2.3 on 2025-07-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="origin_url",
            field=models.URLField(
                default="https://music.163.com/#/artist?id=",
                max_length=500,
                verbose_name="歌手原始网站url",
            ),
        ),
    ]
