# Generated by Django 5.2.3 on 2025-07-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_alter_artist_origin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="origin_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="原始链接"),
        ),
    ]
