# Generated by Django 5.2.3 on 2025-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_alter_song_origin_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image_url",
            field=models.URLField(
                default="", max_length=500, verbose_name="歌曲图片url"
            ),
        ),
    ]
